with Gtk.Window; use Gtk.Window;
with Gtk.Frame; use Gtk.Frame;
with Gtk.Notebook; use Gtk.Notebook;
with Gtk.Box; use Gtk.Box;
with Gtk.Label; use Gtk.Label;
with Gtk.Button; use Gtk.Button;
with Gtk.Alignment; use Gtk.Alignment;
with Gtk.Image; use Gtk.Image;
with Gtk.Tooltips; use Gtk.Tooltips;
package Window1_Pkg is

   type Window1_Record is new Gtk_Window_Record with record
      Frame1 : Gtk_Frame;
      Notebook1 : Gtk_Notebook;
      Vbox1 : Gtk_Vbox;
      Frame2 : Gtk_Frame;
      Vbox2 : Gtk_Vbox;
      Hardware_Status_Label : Gtk_Label;
      Hardware_Button : Gtk_Button;
      Alignment1 : Gtk_Alignment;
      Hbox2 : Gtk_Hbox;
      Image1 : Gtk_Image;
      Label8 : Gtk_Label;
      Label6 : Gtk_Label;
      Frame3 : Gtk_Frame;
      Vbox5 : Gtk_Vbox;
      Web_Status_Label : Gtk_Label;
      Hbox4 : Gtk_Hbox;
      Start_Web : Gtk_Button;
      Alignment2 : Gtk_Alignment;
      Hbox5 : Gtk_Hbox;
      Image2 : Gtk_Image;
      Label13 : Gtk_Label;
      Stop_Web : Gtk_Button;
      Alignment3 : Gtk_Alignment;
      Hbox6 : Gtk_Hbox;
      Image3 : Gtk_Image;
      Label14 : Gtk_Label;
      Label10 : Gtk_Label;
      Frame4 : Gtk_Frame;
      Vbox6 : Gtk_Vbox;
      Database_Status_Label : Gtk_Label;
      Hbox7 : Gtk_Hbox;
      Database_Connect : Gtk_Button;
      Alignment4 : Gtk_Alignment;
      Hbox8 : Gtk_Hbox;
      Image4 : Gtk_Image;
      Label19 : Gtk_Label;
      Database_Disconnect : Gtk_Button;
      Alignment5 : Gtk_Alignment;
      Hbox9 : Gtk_Hbox;
      Image5 : Gtk_Image;
      Label20 : Gtk_Label;
      Label15 : Gtk_Label;
      Label3 : Gtk_Label;
      Label21 : Gtk_Label;
      Label4 : Gtk_Label;
      Label23 : Gtk_Label;
      Label5 : Gtk_Label;
      Image6 : Gtk_Image;
      Label22 : Gtk_Label;
      Frame_Label : Gtk_Label;
   end record;
   type Window1_Access is access Window1_Record'Class;

   procedure Gtk_New (Window1 : out Window1_Access);
   procedure Initialize (Window1 : access Window1_Record'Class);

end Window1_Pkg;
